### ISSUE TITLE
Imperceptible colors on Buffer Names

### ISSUE THREAD

**Issue by wantguns** [casonadams/walh#1]
I think this is the correct place to open the issue, but please let me know if is not.
I love the simplicity of this colorscheme, kudos on that.

My only gripe with it is that the unselected buffer name/titles have the same background and the foreground color. 

Buffer named `style.scss` is present but not visible:
![image](https://user-images.githubusercontent.com/25419159/180920014-54fbd851-96a0-4aef-a10c-f3448f430f78.png)

Buffer named `style.scss` after terminal selection:
![image](https://user-images.githubusercontent.com/25419159/180920094-25560787-f746-49d5-82eb-4507d30b9390.png)

If this is not related to walh, kindly point me to where I should check to get it fixed.
Thanks !

**Comment by casonadams** [comment]
@WantGuns thanks for raising this!  What is the plugin you are using for the tab bar?

**Comment by wantguns** [comment]
Im using barbar -- https://github.com/romgrk/barbar.nvim

**Comment by casonadams** [comment]
@WantGuns I made an update.  I think barbar.nvim is mainstream enough to just include the color highlights it uses into walh.  Please have a look and see if it meets your expectations.

Cheers!

**Comment by wantguns** [comment]
Thanks for the quick fix. 
I can see the buffer names now !
![image](https://user-images.githubusercontent.com/25419159/181037519-337415fe-b343-4afd-8b2e-a06cb90f8229.png)

I think this comes to personal preference, but after your commit, the selected buffer has a darker foreground than the unselected buffer which is confusing my trained muscle memory hehe.

**Comment by casonadams** [comment]
Ah I missed that.  I have corrected this with the last commit.  Give it a look and lets see if it looks fine on your side.

Thanks

**Comment by casonadams** [comment]
@WantGuns can you also share your terminal colorscheme thanks!

**Comment by wantguns** [comment]
Edit: @casonadams I tried switching to a different colorscheme (Hyper) and it looked perfect in that:
![image](https://user-images.githubusercontent.com/25419159/181088928-d59e1cc9-fa85-4a02-ab73-7ffb1b27bff0.png)
I think this has to do with the colorscheme maybe ? 

---
Hey casonadams, I am still facing the same colors on my end after updating the plugin :(

`tmux.conf` is the selected buffer and its foreground is dimmer than the `cpu.tmux` buffer title:
![image](https://user-images.githubusercontent.com/25419159/181084428-ed595961-76b1-4577-b60d-6c299ae6f2cd.png)

**Comment by wantguns** [comment]
For the colorscheme, I wanted to go towards something like Hyper (I really like Vercel's color palette), but it seemed over-contrasted and so I went with Tomorrow Night Bright.

The colors for Alacritty are:
https://github.com/eendroroy/alacritty-theme/blob/master/themes/tomorrow_night_bright.yaml

**Comment by casonadams** [comment]
Thanks for sharing the colorscheme.  So that colorscheme has color15 which is normally light colors (for a dark scheme).  However the white is a darkgrey.  Update the following and it will work for you.

```
    # Default colors
    primary:
      background: '0x000000'
      foreground: '0xeaeaea'

    # Normal colors
    normal:
      black:   '0x000000'
      red:     '0xd54e53'
      green:   '0xb9ca4a'
      yellow:  '0xe6c547'
      blue:    '0x7aa6da'
      magenta: '0xc397d8'
      cyan:    '0x70c0ba'
      white:   '0x424242'

    # Bright colors
    bright:
      black:   '0x666666'
      red:     '0xff3334'
      green:   '0x9ec400'
      yellow:  '0xe7c547'
      blue:    '0x7aa6da'
      magenta: '0xb77ee0'
      cyan:    '0x54ced6'
      white:   '0xeaeaea'
```
Before change:
![image](https://user-images.githubusercontent.com/17597548/181099197-2cf9e795-f8f8-4247-879a-d63617b4d9f0.png)

After change:
![image](https://user-images.githubusercontent.com/17597548/181099111-909d070e-75ab-4781-afe6-bfdc787520e3.png)

The colorscheme can be seen using `neofetch`

**Comment by casonadams** [comment]
I have some other colorschemes that seems to be really nice with `walh` https://github.com/casonadams/alacritty-shell/wiki/Themes

**Comment by wantguns** [comment]
Thanks a lot for the input and quick fixes, im off to checking out your colorschemes for Alacritty !
